---
name: $(BuildDefinitionName)_$(SourceBranchName)_$(date:yyyyMMdd)$(rev:.r)

trigger:
  branches:
    include:
    - main/containers/windows/servercore/2019/*
    exclude:
      - develop
      - bug*
      - feature*
      - main/containers/linux*
      - main/containers/windows/Dockerfile
      - main/containers/windows/build-win-agents.yml
      - main/containers/windows/*.ps1
      - main/.azurepipelines/*
      - README.md

parameters:

  - name: CONTEXT
    displayName: "The the path to your dockerfile"
    default: "containers/windows/servercore"
    type: string

  - name: DOCKERFILE_NAME
    displayName: "The name of the Dockerfile"
    default: "Dockerfile"
    type: string

  - name: NORMAL_USER
    displayName: "The name for the container user, for Windows, can only be ContainerAdministrator or ContainerUser"
    default: "ContainerAdministrator"
    type: string

  - name: REGISTRY
    displayName: "The target registry"
    default: "ghcr.io"
    type: string

  - name: IMAGE_NAME
    displayName: "The name of the image"
    default: "azdo-agent-winsevercoreltsc2022"
    type: string

  - name: PYTHON3_VERSION
    displayName: "The python3 version scoop is expected to install"
    default: "@latest"
    type: string

  - name: TAGS
    displayName: "The tag of the image"
    default: ":latest"
    type: string

  - name: HOSTED_AGENT_IMAGE
    displayName: "The name of the vmImage"
    default: "windows-2022"
    type: string

  - name: SECRETS_VARIABLE_GROUP
    displayName: "The name of the variable group holding the secrets"
    default: "LBDO_DOCKER_SECRETS"
    type: string

  - name: USERNAME
    displayName: "Username to be passed for registry login"
    default: $(USERNAME)
    type: string

  - name: PASSWORD
    displayName: "Password or access token for registry login"
    default: $(PASSWORD)
    type: string

  - name: AZP_SECRETS_VARIABLE_GROUP
    displayName: "The name of the variable group holding the secrets"
    default: "WINDOWS_AZURE_DEVOPS_SECRETS"
    type: string

  - name: AZP_URL
    displayName: "The URL of your Azure DevOps instance, e.g. https://dev.azure.com/example, you should use a secret variable"
    type: string
    default: $(AZP_URL)

  - name: AZP_TOKEN
    displayName: "The PAT token for your Agent to access Azure DevOps, you should use a secret variable"
    default: $(AZP_TOKEN)
    type: string

  - name: AZP_POOL
    displayName: "The pool for your agent to join, you should use a secret variable"
    default: $(AZP_POOL)
    type: string

  - name: AZP_WORK
    displayName: "The default working directory for your agent"
    default: "_work"
    type: string

  - name: TEMPLATE_PATH
    displayName: "The name of the variable group holding the secrets"
    type: string
    default: "../../../../.azurepipelines/.templates/windows/build-windows-container-template.yml"

variables:
  - group: ${{ parameters.SECRETS_VARIABLE_GROUP }}
  - group: ${{ parameters.AZP_SECRETS_VARIABLE_GROUP }}

jobs:
  - template: ${{ parameters.TEMPLATE_PATH }}
    parameters:
      USERNAME: ${{ parameters.USERNAME }}
      PASSWORD: ${{ parameters.PASSWORD }}
      CONTEXT: ${{ parameters.CONTEXT }}
      HOSTED_AGENT_IMAGE: ${{ parameters.HOSTED_AGENT_IMAGE }}
      DOCKERFILE_NAME: ${{ parameters.DOCKERFILE_NAME }}
      REGISTRY: ${{ parameters.REGISTRY  }}
      PYTHON3_VERSION: ${{ parameters.PYTHON3_VERSION }}
      IMAGE_NAME: ${{ parameters.IMAGE_NAME }}
      TAGS: ${{ parameters.TAGS }}
      AZP_URL: ${{ parameters.AZP_URL }}
      AZP_TOKEN: ${{ parameters.AZP_TOKEN }}
      AZP_POOL: ${{ parameters.AZP_POOL }}
      AZP_WORK: ${{ parameters.AZP_WORK }}